// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCX-mgUY1qzffwj-NrnWwOePgCGxPukD9w',
    appId: '1:1058049597820:web:d28c5677f7f53a832544f9',
    messagingSenderId: '1058049597820',
    projectId: 'authapp-8821a',
    authDomain: 'authapp-8821a.firebaseapp.com',
    storageBucket: 'authapp-8821a.firebasestorage.app',
    measurementId: 'G-Q07KY2KRT5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBvzIEADBLnyY57GsaZL_MyC5Lca78yiZ4',
    appId: '1:1058049597820:android:fd0b73f2df8ac4d62544f9',
    messagingSenderId: '1058049597820',
    projectId: 'authapp-8821a',
    storageBucket: 'authapp-8821a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCOzqHP7ilVvxD0g3MWLax5O2aTqUEiTjg',
    appId: '1:1058049597820:ios:7f3da3662d17e6212544f9',
    messagingSenderId: '1058049597820',
    projectId: 'authapp-8821a',
    storageBucket: 'authapp-8821a.firebasestorage.app',
    iosBundleId: 'com.example.task03',
  );
}
